GET http://localhost:3001/api/blogs

###
PUT http://localhost:3001/api/blogs/60c9afdecfb9bc34b8ff6d4a
Content-Type: application/json

{
  "title":"Test Sample edited",
  "author":"pradeep",
  "likes":3000,
  "url":"abc"
}
###
DELETE http://localhost:3001/api/blogs/60c9afdecfb9bc34b8ff6d4a

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title":"Pradeep's quantum physics blog",
  "author":"pradeep",
  "url":"pradeep.com",
  "likes":"7"
}

### 
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWRlZXAyNTcyIiwiaWQiOiI2MGNhYjQ2YmRkOGY4YjE5YTRlMzAyMzUiLCJpYXQiOjE2MjM5MDc0Nzl9.9PPU8dDeFs1QHVx7qkITHHpcUEbtTiLDjturZ9pgTG4

{
  "title":"verifying login with token and posting blog",
  "author":"pradeep",
  "url":"pradeep.com/",
  "likes":10
}